# Generated by Django 2.2.10 on 2020-05-05 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('patronymic', models.CharField(max_length=500)),
                ('SNILS_number', models.CharField(max_length=500)),
                ('SNILS_ctrl', models.IntegerField()),
                ('passportS', models.IntegerField()),
                ('passportN', models.IntegerField()),
                ('district', models.CharField(max_length=500)),
                ('locality', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
