# Generated by Django 2.2.10 on 2020-05-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200506_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='childs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
