# Generated by Django 2.2.10 on 2020-05-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200506_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
