# Generated by Django 2.2.10 on 2020-05-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_profile_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dateOfBirth',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
