# Generated by Django 2.2.10 on 2020-05-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200507_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='SNILS_ctrl',
            field=models.IntegerField(),
        ),
    ]
