# Generated by Django 2.2.10 on 2020-05-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200507_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='childs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='locality',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passportN',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passportS',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=500),
        ),
    ]
